name: Workflows
on:
  push:
    branches:
      - feat-devsecops-osc

jobs:        
  SAST:
    runs-on: ubuntu-latest

    
    steps:

      #requesitos JDK para sonar
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
    
      #copia de proyecto
      - name: Checkout code
        uses: actions/checkout@v2  

     #construccion/compilacion
      - name: Build
        run: | 
          chmod 777 gradlew
          ./gradlew build
    
    #sonarcloud  #actualizacion metodo basico
    #  - name: Analisis SonarCloud
    #    run: |
    #     mvn clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:3.11.0.3922:sonar \
    #     -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
    #     -Dsonar.host.url=https://sonarcloud.io \
    #     -Dsonar.organization=oscargitops \
    #     -Dsonar.projectKey=OscarGitOps_pet-clinic
   

    #  - name: Validando tipo de proyecto
    #    id: tipoProyecto
    #    run: |
    #      pwd
    #      ls -R
    #      if [ -f "build.gradle" ]
    #      then
    #        echo "Proyecto Java"
    #        if grep -q 'id "org.sonarqube" version "3.3"' build.gradle
    #        then
    #          echo "El plugin de SonarCloud ya está presente en build.gradle"
    #        else
    #          sed -i '/id '\''java'\''/a \ \ \ \ id '\''org.sonarqube'\'' version '\''3.3'\''' build.gradle
    #          echo "El plugin de SonarCloud no estaba presente y se ha sido añadido a build.gradle"
    #          cat build.gradle
    #        fi
    #
    #      else
    #        echo "Tipo de proyecto desconocido"
    #      fi
          
      #habilitar ejecucion
      - name: Enable execution gradlew
        run: | 
         chmod 777 gradlew
      
      - name: Run SonarQube analysis
        run: |
         ./gradlew sonarqube \
         -Dsonar.projectKey=OscarGitOps_pet-clinic \
         -Dsonar.organization=oscargitops \
         -Dsonar.host.url=https://sonarcloud.io \
         -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
         -Dsonar.branch.name=feat-devsecops-osc