name: Workflows
on:
  push:
    branches:
      - feat-devsecops-osc

jobs:        
  SAST:
    runs-on: ubuntu-latest

    
    steps:

      #requesitos JDK para sonar
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
    
      #copia de proyecto
      - name: Checkout code
        uses: actions/checkout@v2  

     #construccion/compilacion
      - name: Build
        run: | 
          chmod 777 gradlew
          ./gradlew build
    
    #sonarcloud
      - name: Validando existencia de proyecto en SonarCloud
        id: validateProjectOnSonar
        run: |
          #pwd
          #ls -R
          set +e
          curl -f -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/projects/create' -d 'name=${{ github.event.repository.name }}' -d 'project=${{ github.event.repository.name }}' -d 'organization=oscargitops' -d 'visibility=public'
          if [ $? -ne 0 ]; then
            echo "Proyecto ya existe en Sonarcloud"
          else
            echo "Proyecto ${{ github.event.repository.name }} creado exitosamente en Sonarcloud"
            
            echo "Se establece rama main como rama por defecto"
            curl -X POST -u '${{ secrets.SONAR_TOKEN }}:' 'https://sonarcloud.io/api/project_branches/rename' -d 'name=main' -d 'project=${{ github.event.repository.name }}'
          fi
          set -e