name: Workflows
on:
  push:
    branches:
      - feat-devsecops-osc

jobs:        
  Build:
    runs-on: ubuntu-latest

    
    steps:
     
      ##requisito de SONAR para poder procesar el analisis
      ##seteando maquina ubuntu
      ##version de Java soportado por SONAR

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Checkout code
        uses: actions/checkout@v2  
        
      - name: Log
        run: ls -R

      ##permisos para gradlew y compilación de proyecto
      - name: Build
        run: | 
          chmod 777 gradlew
          ./gradlew build